### ISSUE TITLE
Failed to decrypt a frame for session

### ISSUE THREAD

**Issue by ilinuxadmin** [cbeuw/Cloak#121]
I have the following error on the server:

Jun 29 13:26:09 guest ck-server[2522]: time="2020-06-29T13:26:09Z" level=error msg="Failed to decrypt a frame for session 111641476: extra length is negative or extra length is greater than total pldWithOverHead length"

Environment:
Server: Debian 10
CK-Server 2.2.1
Shadowsocks-libev

Client: iPhone
App: Shadowrocket
Plugin: Cloak

**Comment by beanslel** [comment]
This is a problem with Shadowrocket using an older version of the Cloak client, not a problem with Cloak itself. I already contacted the Shadowrocket developer and they said they would update the Cloak version, but this was several weeks ago and still waiting.

I don't know exactly which version is implemented in Shadowrocket, but as a temporary workaround you can downgrade your Cloak server several versions and it should work again.

**Comment by cbeuw** [comment]
@beanslel 
If Shadowrocket uses a pre-2.1.0 client, then indeed it would be incompatible with 2.1.0+ servers.

**Comment by cbeuw** [comment]
On another note, this is the first time I've heard of Shadowrocket. If they implement the Cloak protocol from scratch there wouldn't have been any licencing issues, but it appears that they bundle Cloak client binaries with their app. Cloak is licenced under GPLv3, what they are doing would have been fine if they include the licence and a link to Cloak's source code in their app. I don't have access to the app so I don't know if they've done that. Additionally if they've modified Cloak's source code, they need to release that under GPLv3 as well. I'm fairly certain they have modified the code, to 1. make Cloak work on iOS and 2. fix bugs, as indicated from their changelog.

It looks as though Shadowrocket is entirely proprietary, and from this repo's GitHub insight, the fixes mentioned in Shadowrocket's changelogs do not appear in any of the forked repos (the code could have been hosted elsewhere of course, but I didn't find any).

**Comment by beanslel** [comment]
Hah, I didn't notice it but funnily enough Shadowrocket was updated 10h after this issue was raised and now it works again with the latest Cloak version.

Shadowrocket has been around for a while, it bundles ss/v2ray/cloak into a single app so it's convenient. I had a quick look and there is a link to this github in the app, but it does not appear to include the license.

Maybe you can email the dev about it, the email is buginapp at gmail dot com

**Comment by cbeuw** [comment]
@beanslel Thanks for the info. I'm fine with them just leaving a link, but the main GPL issue is the modified source code. I couldn't test Cloak on iOS because I don't have a mac (thanks apple), but if someone else managed to do it that involves modification of Cloak, it'd be great (and indeed required by the licence) that they release it under a GPLv3 compatible licence.

I'll contact the devs regarding this. Thanks!

**Comment by ilinuxadmin** [comment]
I have updated Shadowrocket to the latest version and it worked!
Thank you all.
