### ISSUE TITLE
userinfo.db

### ISSUE THREAD

**Issue by lwyh** [cbeuw/Cloak#13]
How do I create userinfo.db? I get an error message when I start ss-server because userinfo.db does not exist.

**Comment by cbeuw** [comment]
What OS are you using? userinfo.db should be created automatically to the current directory if it doesn't exist. Make sure you have permission to create files in the directory you start ss-server

**Comment by lwyh** [comment]
Server is running Ubuntu 18.04. 

All steps are done as root.

shadowsocks-libev listens on port 443. There is a web server listening on port 8443.

shadowsocks-libev is configured with:

```
    "plugin":"/usr/local/bin/ck-server",
    "plugin_opts":"/etc/ck-server/config.json"
```

The configuration file `/etc/ck-server/config.json` looks like this:

```
{
"WebServerAddr":"127.0.0.1:8443",
"PrivateKey":"UKc1jvZgl0vFqP3Cpw23wyfoTod8yWHCf87MsKvLglY=",
"AdminUID":"IS0rRsd8HNtnWLmnxvPMtQfUtE0GoJ2GmPio+CSYbkk=",
"DatabasePath":"userinfo.db",
"BackupDirPath":""
}
```

Shadowsocks-libev is started by systemd:

```
systemctl restart shadowsocks-libev
```

**Comment by cbeuw** [comment]
DatabasePath field of the config file is a relative path, Cloak will attempt to create userinfo.db at the current working directory. For systemctl services I believe that's /. This is most likely not where you want to put the userinfo.db and it may have trouble creating it.

Try to change DatabasePath to an absolute path like /home/[your username]/[some sub directories]/userinfo.db. Do the same to BackupDirPath as well because otherwise ck-server will attempt to create database backups under /

**Comment by lwyh** [comment]
Yes, it was a permissions problem, thanks. Testing completed successfully.

**Comment by asmadeus08** [comment]
The same problem but advice doesn't help at all. Try to use the same config and Ubuntu version the same but error still appears.
