### ISSUE TITLE
Will Cloak implement XTLS technology in the future?

### ISSUE THREAD

**Issue by windstander** [cbeuw/Cloak#139]
It's said XTLS is very fast and much faster than tls.

**Comment by windstander** [comment]
https://github.com/XTLS/Go

**Comment by cbeuw** [comment]
Cloak doesn't actually implement the TLS spec, it just makes it look identical superficially. The version or variant of protocols used by Cloak must also be widely used, as one of our primary means to evict censorship is by "blending in" and raising the potential collateral damage due to false positives.

If Cloak were to adapt a novel protocol, no matter how good it is by technical merits, it risks of being singled out and detected. And indeed I don't think Cloak will benefit much from the features of the protocol, as it will never fully implement it.

**Comment by windstander** [comment]
> 
> 
> Cloak doesn't actually implement the TLS spec, it just makes it look identical superficially. The version or variant of protocols used by Cloak must also be widely used, as one of our primary means to evict censorship is by "blending in" and raising the potential collateral damage due to false positives.
> 
> If Cloak were to adapt a novel protocol, no matter how good it is by technical merits, it risks of being singled out and detected. And indeed I don't think Cloak will benefit much from the features of the protocol, as it will never fully implement it.

OK. Thank you for your plugin.
