### ISSUE TITLE
Can't afford many concurrent?

### ISSUE THREAD

**Issue by malikshi** [cbeuw/Cloak#14]
Hei. I just want to ask. I running it with double server with different port. After 2 hours testing one of server shutdown. now I  running only one server. How many concurrent that ckserver handle?
NB: I set user 100concurrrent.

**Comment by cbeuw** [comment]
If there are two ck-server instances, they should be independent from each other and how many you can run concurrently depends on the system spec. But the two instances cannot use the same userinfo.db because boltdb puts a mutex lock on the file so only one ck-server can access it.

Did you manage to get the log from the one that got shut down?

**Comment by malikshi** [comment]
here my spec @cbeuw 
VPS Openvz 7
Ubuntu 16.04
RAM 2GB
I/O etc was great
after your answer, I trying to run only one server but its error again after a few hours these the log you can see in the pic.
![screenshot_752](https://user-images.githubusercontent.com/9080737/53299635-80816600-386f-11e9-984b-2d535db1628c.png)

**Comment by cbeuw** [comment]
Did you happen to put the server's own pubic IP address in WebServerAddr?

**Comment by malikshi** [comment]
> Did you happen to put the server's own pubic IP address in WebServerAddr?

nope, i put joox instead bing like your example

**Comment by cbeuw** [comment]
1. What's the output of `ulimit -n` on your system?

2. Is there anything like a firewall log that shows where the connections came from as the server crashes?

**Comment by malikshi** [comment]
its work, need help in openwrt, your ck-client doesn't seem work, it says to install haveged. how to install it?
