### ISSUE TITLE
Can RedirAddr be set to a domain?

### ISSUE THREAD

**Issue by windstander** [cbeuw/Cloak#70]
Set to a domain not an IP?

**Comment by cbeuw** [comment]
Yes it can be a domain

**Comment by windstander** [comment]
> 
> 
> Yes it can be a domain

Thus, setting both rediraddr and ServerName to bing.com or setting redireaddr to the IP of bing.com, which is better? If one day the IP of bing.com is changed, the ladder setting will cause cloak to malfunction?

**Comment by cbeuw** [comment]
Setting RedirAddr to bing.com would be better. As you mentioned, the IP may change one day. However, regardless how RedirAddr and ServerName are set, the core functionalities of Cloak will not be affected because it doesn’t check them. ServerName is only for the firewall on the client side to see and RedirAddr is for active probers
